import { REDIRECTS } from "./lib/redirects.mjs";

const SITE = "https://www.icecubedigital.com";

/**
 * Same-domain absolute destinations → paths. Keeps redirects host-relative so
 * they resolve correctly on preview deployments (a hardcoded www URL would bounce
 * preview traffic to production). External URLs are passed through untouched.
 */
function toDestination(to) {
  if (to.startsWith(SITE)) return to.slice(SITE.length) || "/";
  return to;
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "www.icecubedigital.com",
        pathname: "/**",
      },
    ],
  },
  // Legacy URL redirects — edit the list in lib/redirects.js, not here.
  async redirects() {
    return REDIRECTS.map(([source, to]) => ({
      source,
      destination: toDestination(to),
      statusCode: 301,
    }));
  },

  /**
   * Cache-Control for everything served out of /public.
   *
   * Vercel's default for static files is `public, max-age=0`, which tells both
   * the browser AND Cloudflare not to cache. That is why every asset came back
   * `cf-cache-status: DYNAMIC` — each font, stylesheet and image was making a
   * full round trip to the Vercel origin instead of being served from the
   * visitor's nearest Cloudflare edge. Cloudflare caches these file types by
   * default; it just needs the origin to permit it.
   *
   * TTLs differ per directory because these filenames are NOT content-hashed
   * (unlike /_next/static/*, which Next already marks immutable). A long TTL on
   * a file that gets overwritten in place would strand users on a stale copy,
   * so only genuinely immutable assets get the one-year treatment.
   */
  async headers() {
    return [
      {
        // Gilroy woff2 files. Never edited in place — a new weight means a new
        // filename, so this is safe to freeze.
        source: "/fonts/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        // Images, icons, flags, SVGs. Long but not immutable: if you replace an
        // image while keeping its filename, purge the Cloudflare cache or it
        // will serve the old one until this expires.
        source: "/assets/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=2592000" }],
      },
      {
        // Vendor libs (jquery, owl.carousel) are pinned; common-next.js and
        // load-design.js do get edited. A day of edge caching with a week of
        // stale-while-revalidate keeps it fast without delaying a fix.
        source: "/js/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=86400, stale-while-revalidate=604800" }],
      },
      {
        // output.css is regenerated by `npm run build:css` and keeps its name,
        // so this stays deliberately short — long enough for Cloudflare to edge
        // cache it, short enough that a rebuild reaches visitors within the hour.
        source: "/css/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=3600, stale-while-revalidate=86400" }],
      },
    ];
  },
};

export default nextConfig;

