// HTML sitemap content — mirrors https://www.icecubedigital.com/sitemap/.
// A section has either `groups` (labelled sub-lists) or a flat `links` array.
// Homoglyph-corrupted labels and one wrong href from live were corrected.

export const SITEMAP_SECTIONS = [
  {
    title: "Website Design & Development",
    groups: [
      {
        subtitle: "eCommerce",
        links: [
          { label: "eCommerce Website Design", href: "/ecommerce-website-design-services/" },
          { label: "Ecommerce Website Development", href: "/ecommerce-website-development-services/" },
          { label: "Hire eCommerce Developers", href: "/hire-ecommerce-designers-developers/" },
          { label: "Website Maintenance Service", href: "/website-maintenance-service/" },
        ],
      },
      {
        subtitle: "Magento",
        links: [
          { label: "Magento Development", href: "/magento-development-services/" },
          { label: "Magento 2 Development", href: "/magento-2-development-services/" },
          { label: "Magento Website Design", href: "/magento-website-design/" },
          { label: "Hire Magento Developers", href: "/hire-magento-2-developers-programmers/" },
          { label: "Magento 2 Upgrade and Migration", href: "/magento-2-upgrade-and-migration-services/" },
          { label: "Magento Maintenance", href: "/magento-maintenance-services/" },
        ],
      },
      {
        subtitle: "WordPress",
        links: [
          { label: "WordPress Development", href: "/wordpress-development-services/" },
          { label: "WordPress Website Design", href: "/wordpress-website-design-company/" },
          { label: "Hire WordPress Developers", href: "/hire-wordpress-developers-designers/" },
          { label: "WordPress Maintenance", href: "/wordpress-maintenance-service/" },
          { label: "WordPress VIP", href: "/wordpress-vip/" },
          { label: "Hire WordPress VIP Developers", href: "/hire-wordpress-vip-developers/" },
          { label: "WordPress VIP Maintenance", href: "/wordpress-vip-support-and-maintenance/" },
          { label: "WordPress Development UK", href: "/wordpress-development-company-uk/" },
        ],
      },
      {
        subtitle: "Shopify",
        links: [
          { label: "Shopify Development", href: "/shopify-development-services/" },
          { label: "Shopify Website Design", href: "/shopify-website-design/" },
          { label: "Shopify Plus Development", href: "/shopify-plus-development-agency/" },
          { label: "Hire Shopify Plus Developer", href: "/hire-shopify-plus-developers/" },
          { label: "Hire Shopify Developers", href: "/hire-shopify-developers-experts/" },
          { label: "Hire Shopify Designers", href: "/hire-shopify-website-designers/" },
          { label: "Shopify Maintenance and Support", href: "/shopify-maintenance-services/" },
          { label: "Shopify Development UK", href: "/shopify-development-company-uk/" },
          { label: "BigCommerce to Shopify Migration", href: "/bigcommerce-to-shopify-migration-services/" },
          { label: "WooCommerce to Shopify Migration", href: "/woocommerce-to-shopify-migration-services/" },
          { label: "Magento to Shopify Migration", href: "/magento-to-shopify-migration-services/" },
        ],
      },
      {
        subtitle: "JavaScript",
        links: [
          { label: "AngularJs Development", href: "/angular-js-development/" },
          { label: "ReactJS Development", href: "/reactjs-development-services/" },
          { label: "NodeJS Development", href: "/nodejs-development-services/" },
          { label: "Hire ReactJS Developers", href: "/hire-reactjs-developers/" },
          { label: "Hire NodeJS Developers", href: "/hire-nodejs-developers/" },
          { label: "Hire NextJS Developers", href: "/hire-next-js-developers/" },
        ],
      },
      {
        subtitle: "WooCommerce / Webflow",
        links: [
          { label: "WooCommerce Development", href: "/woocommerce-development-services/" },
          { label: "Hire WooCommerce Developers", href: "/hire-woocommerce-developers-experts/" },
          { label: "Webflow Development", href: "/webflow-development-agency/" },
          { label: "Hire Webflow Developers", href: "/hire-webflow-developers/" },
          { label: "Webflow Maintenance", href: "/webflow-maintenance-services/" },
        ],
      },
      {
        subtitle: "White Label",
        links: [
          { label: "White Label Web Design and Development", href: "/white-label-web-design-and-development-services/" },
          { label: "White Label Magento Development", href: "/white-label-magento-development/" },
          { label: "White Label WordPress Development", href: "/white-label-wordpress-development/" },
          { label: "White Label Shopify Development", href: "/white-label-shopify-development/" },
          { label: "White Label PPC", href: "/white-label-ppc-services/" },
          { label: "White Label WordPress Maintenance", href: "/white-label-wordpress-maintenance-services/" },
        ],
      },
      {
        subtitle: "PHP / Other",
        links: [
          { label: "PHP Development", href: "/custom-php-development-services/" },
          { label: "Laravel Development UK", href: "/laravel-development-company-uk/" },
          { label: "Codeigniter Development", href: "/codeigniter-development-services/" },
          { label: "Joomla Development", href: "/joomla-development-services/" },
          { label: "Mobile App Development", href: "/mobile-application/" },
          { label: "Development Partnership", href: "/development-partnership/" },
        ],
      },
    ],
  },
  {
    title: "Digital Marketing Services",
    links: [
      { label: "Professional SEO Services", href: "/seo-search-engine-optimization/" },
      { label: "Local SEO Services", href: "/local-seo-services/" },
      { label: "International SEO Services", href: "/international-seo-services/" },
      { label: "On Page SEO Services", href: "/on-page-seo-services/" },
      { label: "Technical SEO Services", href: "/technical-seo-services/" },
      { label: "Amazon SEO Services", href: "/amazon-seo-services/" },
      { label: "Hire SEO Experts", href: "/hire-seo-experts/" },
      { label: "White Label SEO", href: "/white-label-seo-services/" },
      { label: "Ecommerce SEO Services", href: "/ecommerce-seo-services/" },
      { label: "Magento SEO Services", href: "/magento-seo-services/" },
      { label: "WordPress SEO Service", href: "/wordpress-seo-service/" },
      { label: "Shopify SEO Services", href: "/shopify-seo-service/" },
      { label: "Shopify Plus SEO Services", href: "/shopify-plus-seo-services/" },
      { label: "WooCommerce SEO Service", href: "/woocommerce-seo-service/" },
      { label: "Digital Marketing Services", href: "/digital-marketing-service/" },
      { label: "Digital Marketing Analytics & Reporting", href: "/digital-marketing-analytics-reporting-services/" },
      { label: "Email Marketing Services", href: "/email-marketing-company/" },
      { label: "Klaviyo Marketing Services", href: "/klaviyo-email-marketing-agency/" },
      { label: "Social Media Advertising", href: "/social-media-advertising-services/" },
      { label: "Social Media Marketing Management", href: "/social-media-marketing-management/" },
      { label: "SaaS Digital Marketing", href: "/saas-digital-marketing-agency/" },
      { label: "Performance Marketing", href: "/performance-marketing-services/" },
      { label: "Pay-Per-Click Services", href: "/ppc-management-services/" },
      { label: "Amazon PPC Management", href: "/amazon-ppc-management-services/" },
      { label: "Conversion Rate Optimization", href: "/conversion-rate-optimization/" },
    ],
  },
  {
    title: "AI Services",
    links: [
      { label: "AI Consulting Services", href: "/ai-consulting-services/" },
      { label: "AI Integration Services", href: "/ai-integration-services/" },
      { label: "AI SEO Services", href: "/ai-seo-services/" },
      { label: "AI Digital Marketing Services", href: "/ai-digital-marketing-services/" },
      { label: "AI in eCommerce", href: "/ai-in-ecommerce-solutions/" },
      { label: "ChatGPT Advertising Services", href: "/chatgpt-advertising-services/" },
      { label: "Marketing Automation Services", href: "/marketing-automation-services/" },
    ],
  },
  {
    title: "Industry Website Design & Development",
    links: [
      { label: "Jewellery", href: "/jewelry-website-design-development/" },
      { label: "Furniture", href: "/furniture-website-design-development/" },
      { label: "School", href: "/school-website-design/" },
      { label: "Electrician", href: "/electrician-web-design-services/" },
      { label: "Firearm", href: "/gun-and-firearm-website-design-development/" },
      { label: "Automotive", href: "/automotive-website-design/" },
      { label: "Medical & Healthcare", href: "/medical-healthcare-website-design-development/" },
      { label: "Fashion", href: "/fashion-website-design/" },
      { label: "Restaurant", href: "/restaurant-website-design-development/" },
      { label: "Blinds & Curtains", href: "/blinds-website-design-development/" },
      { label: "Hair Salon", href: "/hair-salon-website-design/" },
      { label: "Sports", href: "/sports-website-design/" },
      { label: "Travel & Tourism", href: "/travel-website-design-development/" },
      { label: "HVAC", href: "/hvac-website-design/" },
      { label: "Legal", href: "/law-firm-website-design-development/" },
      { label: "Jewelry Order Portal", href: "/custom-jewelry-web-portal-development/" },
      { label: "Real Estate", href: "/real-estate-website-design-development/" },
      { label: "Food", href: "/food-beverage-website-design/" },
      { label: "Cleaning", href: "/cleaning-company-web-design-company/" },
      { label: "Plumber", href: "/plumbers-web-design-services/" },
    ],
  },
  {
    title: "SEO Solutions for Industry",
    links: [
      { label: "HVAC SEO Services", href: "/hvac-seo-services/" },
      { label: "Medical SEO Services", href: "/medical-seo-services/" },
      { label: "Dental SEO Services", href: "/dental-seo-services/" },
      { label: "Cleaning Company SEO Services", href: "/seo-for-cleaning-company/" },
      { label: "Funeral Home SEO Services", href: "/funeral-home-seo/" },
      { label: "Plumber SEO Services", href: "/plumber-seo-services/" },
      { label: "Cannabis SEO Services", href: "/cannabis-marketing-seo-service/" },
      { label: "Real Estate SEO Services", href: "/real-estate-seo-services/" },
      { label: "Manufacturing SEO Services", href: "/manufacturing-seo-company/" },
      { label: "Automotive SEO Services", href: "/automotive-seo-company/" },
      { label: "Fitness SEO Services", href: "/fitness-seo-and-digital-marketing/" },
      { label: "Restaurant SEO Services", href: "/seo-for-restaurants/" },
      { label: "Roofing SEO Services", href: "/roofing-seo-company/" },
      { label: "Law Firm SEO Services", href: "/law-firm-seo-services/" },
      { label: "Fashion SEO Services", href: "/fashion-seo-services/" },
      { label: "Electrician SEO Services", href: "/electrician-seo-services/" },
      { label: "Painter SEO Services", href: "/painter-seo-services/" },
    ],
  },
  {
    title: "Locations",
    links: [
      { label: "Atlanta SEO Services Company", href: "/atlanta-seo-services-company/" },
      { label: "San Francisco SEO Company", href: "/san-francisco-seo-company/" },
      { label: "Houston SEO Company", href: "/houston-seo-company/" },
      { label: "Philadelphia SEO Company", href: "/philadelphia-seo-company/" },
      { label: "San Diego SEO Company", href: "/san-diego-seo-company/" },
      { label: "The Woodlands SEO Company", href: "/the-woodlands-seo-company/" },
      { label: "Los Angeles SEO Company", href: "/los-angeles-seo-company/" },
      { label: "Austin SEO Company", href: "/austin-seo-company/" },
      { label: "Miami SEO Company", href: "/miami-seo-company/" },
      { label: "NYC SEO Company", href: "/nyc-seo-company/" },
      { label: "Chicago SEO Company", href: "/chicago-seo-company/" },
      { label: "Denver SEO Agency", href: "/denver-seo-agency/" },
      { label: "Las Vegas SEO Company", href: "/las-vegas-seo-company/" },
      { label: "Boston SEO Services", href: "/boston-seo-services/" },
      { label: "Seattle SEO Company", href: "/seattle-seo-company/" },
      { label: "Pittsburgh SEO Company", href: "/pittsburgh-seo-company/" },
      { label: "Dallas SEO Consultant", href: "/dallas-seo-consultant/" },
      { label: "SEO Company in Gujarat", href: "/seo-company-gujarat/" },
      { label: "SEO Company in Ahmedabad", href: "/seo-company-ahmedabad/" },
    ],
  },
  {
    title: "Company",
    links: [
      { label: "About Us", href: "/about-us/" },
      { label: "Why Work With Us", href: "/why-work-with-us/" },
      { label: "Web Design FAQs", href: "/ecommerce-website-design-development-faqs/" },
      { label: "Career", href: "/career/" },
    ],
  },
  {
    title: "Our Work",
    links: [
      { label: "Our Portfolio", href: "/our-portfolio/" },
      { label: "Case Studies", href: "/case-studies/" },
    ],
  },
  {
    title: "Resources",
    links: [
      { label: "Testimonials", href: "/client-testimonials/" },
      { label: "Our Blog", href: "/blog/" },
      { label: "Meta Length Checker", href: "/meta-length-checker/" },
      { label: "Newsletter", href: "/web-wednesday-newsletter/" },
      { label: "Learning", href: "/learning/" },
    ],
  },
  {
    title: "Other Links",
    links: [
      { label: "Contact Us", href: "/contact-us/" },
      { label: "Privacy Policy", href: "/privacy-policy/" },
      { label: "Scam Alert", href: "/important-update-regarding-scammers/" },
    ],
  },
];
